name: Deployment pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  DATABASE_URL: ${{secrets.DATABASE_URL}}
  SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  DAILY_HEARDLE_CRON_UTC_HOUR: ${{ secrets.DAILY_HEARDLE_CRON_UTC_HOUR }}
  DAILY_HEARDLE_CRON_UTC_MINUTE: ${{ secrets.DAILY_HEARDLE_CRON_UTC_MINUTE }}
  UNLIMITED_HEARDLE_CRON_UTC_HOUR: ${{ secrets.UNLIMITED_HEARDLE_CRON_UTC_HOUR }}
  UNLIMITED_HEARDLE_CRON_UTC_MINUTE: ${{ secrets.UNLIMITED_HEARDLE_CRON_UTC_MINUTE }}
  WEBHOOK_URL: ${{secrets.WEBHOOK_URL}}
  PORT: ${{secrets.PORT}}
  WHITELISTED_DOMAINS: ${{ secrets.WHITELISTED_DOMAINS }}
  PAPERTRAIL_API_TOKEN: ${{ secrets.PAPERTRAIL_API_TOKEN}}
  DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
  REDIS_URL: ${{ secrets.REDIS_URL }}
  PROXY_URIS: ${{ secrets.PROXY_URIS }}
  VERCEL_WEBHOOK_SECRET: ${{ secrets.VERCEL_WEBHOOK_SECRET}}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID}}
  VERCEL_API_TOKEN: ${{ secrets.VERCEL_API_TOKEN}}

jobs:
  unit_tests:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install dependencies
        run: yarn install
      - name: Unit tests
        run: yarn test
  # deploy:
  #   needs: [unit_tests]
  #   if: github.event_name == 'push'
  #   runs-on: ubuntu-24.04
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: akhileshns/heroku-deploy@v3.13.15
  #       with:
  #         heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
  #         heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
  #         heroku_email: ${{ secrets.HEROKU_EMAIL }}
  tag_release:
    needs: [unit_tests]
    if: github.event_name == 'push'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true
      - name: Test Success
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ success() }}
        with:
          severity: info
          details: Deployment pipeline succeeded!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Test Failure
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ failure() }}
        with:
          severity: error
          details: Deployment pipeline failed...
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
